name: Build website

on:
  push:
    branches:
      - main
      - master
      - actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Generate dotenv file
        run: |
          cat <<EOF | tee -a .env.default
          HUGO_VERSION=0.81.0
          EMACS_VERSION=27.1
          NODE_VERSION=14
          EOF
          # some configurable environment variables
          tee -a .env.secrets <<< "$DOTENV"
          grep -hs ^ .env.default .env.local .env .env.secrets | tee .env.final
        env:
          DOTENV: ${{ secrets.DOTENV }}

      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env.final

      - uses: purcell/setup-emacs@v3.0
        with:
          version: '${{ env.EMACS_VERSION }}'

      - name: Cache emacs dependencies
        uses: actions/cache@v2
        with:
          path: .emacs.d
          key: ${{ runner.os }}-emacs-${{ steps.env.outputs.EMACS_VERSION }}-${{ hashFiles('**/*.el') }}
          restore-keys: |
            ${{ runner.os }}-emacs-${{ steps.env.outputs.EMACS_VERSION }}-

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '${{ env.HUGO_VERSION }}'
          extended: true

      - name: Cache hugo modules
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: make all

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
