name: Build website

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Get environment variables
        id: env
        run: |
          if [[ -f .env ]]; then . .env; fi
          echo "::set-output name=HUGO_VERSION::${HUGO_VERSION:-latest}"
          echo "::set-output name=EMACS_VERSION::${EMACS_VERSION:-27.1}"

      - uses: purcell/setup-emacs@v3.0
        with:
          version: '${{ steps.env.outputs.EMACS_VERSION }}'

      - name: Cache emacs dependencies
        uses: actions/cache@v2
        with:
          path: .emacs.d
          key: ${{ runner.os }}-emacs-${{ steps.env.outputs.EMACS_VERSION }}-${{ hashFiles('**/*.el') }}
          restore-keys: |
            ${{ runner.os }}-emacs-${{ steps.env.outputs.EMACS_VERSION }}-

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '${{ steps.env.outputs.HUGO_VERSION }}'
          extended: true

      - name: Cache hugo modules
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: make all

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
